# Generated by Django 5.0.3 on 2024-04-03 14:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='end_data',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_data',
        ),
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='session',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default='17:19'),
        ),
        migrations.AddField(
            model_name='session',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default='17:19'),
        ),
        migrations.AlterField(
            model_name='session',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_film', to='cinema.film'),
        ),
        migrations.AlterField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_hall', to='cinema.cinemahall'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
