# Generated by Django 5.0.3 on 2024-04-06 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_session_options_session_occupied_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='data_session',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default='02:10'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default='02:10'),
        ),
    ]
