# Generated by Django 5.0.3 on 2024-04-07 22:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_ticket_data_session_alter_session_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-data_session']},
        ),
        migrations.RemoveField(
            model_name='session',
            name='occupied_seats',
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default='01:15'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default='01:15'),
        ),
        migrations.CreateModel(
            name='AvailableSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('occupied_seats', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.session')),
            ],
            options={
                'unique_together': {('session', 'date')},
            },
        ),
    ]
