# Generated by Django 5.0.3 on 2024-04-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_session_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-data_creation']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='data_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default='18:38'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default='18:38'),
        ),
    ]
