# Generated by Django 4.2 on 2024-04-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_alter_cinemahall_name_alter_film_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default='01:06'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default='01:06'),
        ),
    ]
